# Generated by Django 4.1.1 on 2022-09-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studentNum", models.CharField(max_length=7)),
                ("A1_marker", models.CharField(max_length=7)),
                ("A2_marker", models.CharField(max_length=7)),
                ("A3_marker", models.CharField(max_length=7)),
                ("A4_marker", models.CharField(max_length=7)),
                ("A5_marker", models.CharField(max_length=7)),
                ("A6_marker", models.CharField(max_length=7)),
            ],
            options={
                "db_table": "Allocation Table",
            },
        ),
        migrations.CreateModel(
            name="AssessmentTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=20)),
                ("dueDate", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "Assessment Table",
            },
        ),
        migrations.CreateModel(
            name="ExtensionRequestTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studentNum", models.CharField(max_length=8)),
                (
                    "extensionReason",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("numDays", models.IntegerField()),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("assessment", models.CharField(blank=True, max_length=7, null=True)),
                ("reasoning", models.CharField(blank=True, max_length=200, null=True)),
                ("file", models.FileField(max_length=254, upload_to=None)),
                (
                    "convenorMessage",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "db_table": "Extension Request Table",
            },
        ),
        migrations.CreateModel(
            name="MarksTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student", models.CharField(max_length=7)),
                ("A1", models.FloatField(blank=True, null=True)),
                ("A2", models.FloatField(blank=True, null=True)),
                ("A3", models.FloatField(blank=True, null=True)),
                ("A4", models.FloatField(blank=True, null=True)),
                ("A5", models.FloatField(blank=True, null=True)),
                ("A6", models.FloatField(blank=True, null=True)),
                ("T1", models.FloatField(blank=True, null=True)),
                ("T2", models.FloatField(blank=True, null=True)),
                ("final1016", models.FloatField(blank=True, null=True)),
                ("A_avg1016", models.FloatField(blank=True, null=True)),
                ("Test_avg1016", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "MarksTable",
            },
        ),
        migrations.CreateModel(
            name="QueryTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studentNum", models.CharField(max_length=8)),
                ("queryType", models.CharField(blank=True, max_length=20, null=True)),
                ("query", models.CharField(blank=True, max_length=200, null=True)),
                ("assignedTo", models.CharField(blank=True, max_length=20, null=True)),
                ("status", models.CharField(blank=True, max_length=7, null=True)),
                ("file", models.FileField(max_length=254, upload_to=None)),
                (
                    "responseMessage",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "db_table": "Query Table",
            },
        ),
    ]
