# Generated by Django 4.1.1 on 2022-09-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_allocationtable_assessmenttable_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocateTutors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
            ],
            options={
                "db_table": "Allocate Tutors",
            },
        ),
        migrations.CreateModel(
            name="classReps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stuNumber", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "class Representatives",
            },
        ),
        migrations.CreateModel(
            name="UploadAssignmentMarks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
            ],
            options={
                "db_table": "Upload Assignment Marks",
            },
        ),
        migrations.CreateModel(
            name="UploadStudentMarks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
            ],
            options={
                "db_table": "Upload Student Marks",
            },
        ),
        migrations.AlterField(
            model_name="extensionrequesttable",
            name="file",
            field=models.ImageField(upload_to=None),
        ),
    ]
