# Generated by Django 4.1.1 on 2022-09-25 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_allocatetutors_classreps_uploadassignmentmarks_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalQueries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicalCertificate", models.FileField(upload_to=None)),
                ("extensionDays", models.IntegerField()),
                (
                    "queryDetails",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Medical Queries",
            },
        ),
    ]
