# Generated by Django 4.1.1 on 2022-09-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_medicalqueries_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocatetutors",
            name="file",
            field=models.FileField(upload_to="media"),
        ),
        migrations.AlterField(
            model_name="medicalqueries",
            name="medicalCertificate",
            field=models.FileField(upload_to="media"),
        ),
        migrations.AlterField(
            model_name="querytable",
            name="file",
            field=models.FileField(max_length=254, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="uploadassignmentmarks",
            name="file",
            field=models.FileField(upload_to="media"),
        ),
        migrations.AlterField(
            model_name="uploadstudentmarks",
            name="file",
            field=models.FileField(upload_to="media"),
        ),
    ]
