# Generated by Django 4.1.1 on 2022-09-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_allocatetutors_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="querytable",
            name="assignedTo",
        ),
        migrations.RemoveField(
            model_name="querytable",
            name="file",
        ),
    ]
