# Generated by Django 4.1.1 on 2022-09-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_querytable_assignedto_remove_querytable_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompassionateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studentNumber", models.CharField(default=1, max_length=10)),
                ("proofOfReason", models.FileField(upload_to="media")),
                ("extensionDays", models.IntegerField()),
                (
                    "requestDetails",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
            options={
                "db_table": "Compassionate Request",
            },
        ),
    ]
