# Generated by Django 4.1.1 on 2022-09-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_compassionaterequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="querytable",
            name="responseMessage",
        ),
        migrations.RemoveField(
            model_name="querytable",
            name="status",
        ),
        migrations.AddField(
            model_name="querytable",
            name="assigned_to",
            field=models.CharField(
                choices=[("convenor", "CONVENOR"), ("tutor", "TUTOR")],
                default="convenor",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="querytable",
            name="queryType",
            field=models.CharField(
                choices=[
                    ("content", "CONTENT"),
                    ("assessment marking", "ASSESSMENT MARKING"),
                    ("other", "OTHER"),
                ],
                default="content",
                max_length=20,
            ),
        ),
    ]
