# Generated by Django 4.1.1 on 2022-09-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_querytable_responsemessage_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="querytable",
            old_name="query",
            new_name="queryDetails",
        ),
    ]
