# Generated by Django 4.1.1 on 2022-09-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_querytable_responsemessage_querytable_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompassionateResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentNumber', models.CharField(default=1, max_length=10)),
                ('status', models.CharField(choices=[('approved', 'approved'), ('not approved', 'NOT APPROVED')], default='not responded', max_length=20)),
                ('responseMessage', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Compassionate Table Response',
            },
        ),
        migrations.CreateModel(
            name='MedicalResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentNumber', models.CharField(default=1, max_length=10)),
                ('status', models.CharField(choices=[('approved', 'approved'), ('not approved', 'NOT APPROVED')], default='not responded', max_length=20)),
                ('responseMessage', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Medical Table Response',
            },
        ),
        migrations.CreateModel(
            name='QueryTableResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentNumber', models.CharField(default=1, max_length=10)),
                ('status', models.CharField(choices=[('responded', 'RESPONDED'), ('not responded', 'NOT RESPONDED')], default='not responded', max_length=20)),
                ('responseMessage', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Query Table Response',
            },
        ),
        migrations.RemoveField(
            model_name='querytable',
            name='responseMessage',
        ),
        migrations.RemoveField(
            model_name='querytable',
            name='status',
        ),
    ]
