# Generated by Django 4.1.1 on 2022-09-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_compassionateresponse_medicalresponse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadstudentmarks",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="media"),
        ),
    ]
